package workspace

import (
	"context"
	"errors"
	"github.com/JoaoGabrielVianna/lightweight-saas-backend/internal/audit"
	"strings"
	"testing"

	"github.com/JoaoGabrielVianna/lightweight-saas-backend/internal/publicid"
)

const (
	fixtureIDProd    = "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
	fixtureIDStaging = "5a1b2c3d-4e5f-4a6b-8c9d-0e1f2a3b4c5d"
	fixtureIDOld     = "7b8c9d0e-1f2a-4b3c-9d4e-5f6a7b8c9d0e"
)

func ctx() context.Context { return context.Background() }

// ---------------------------------------------------------------------------
// NewService
// ---------------------------------------------------------------------------

// TestNewService_NilRepositoryYieldsNil pins the "domain not wired" signal the
// composition root reads. Returning a usable Service over a nil repository
// would turn a wiring mistake into a panic on the first request instead of a
// route that was never mounted.
func TestNewService_NilRepositoryYieldsNil(t *testing.T) {
	if NewService(nil, &fakeRunner{}, &fakeAuditWriter{}) != nil {
		t.Error("NewService(nil) must return nil so the router omits the routes")
	}
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

func TestCreate_DerivesSlugFromNameWhenAbsent(t *testing.T) {
	svc, _ := newTestService()

	w, err := svc.Create(ctx(), CreateInput{Name: "  Production EU  "}, testEvent(audit.ActionWorkspaceCreated))
	if err != nil {
		t.Fatalf("Create: %v", err)
	}

	if w.Slug != "production-eu" {
		t.Errorf("slug = %q, want %q", w.Slug, "production-eu")
	}
	if w.Name != "Production EU" {
		t.Errorf("name = %q, want it trimmed but not slugified", w.Name)
	}
	if w.Status != StatusActive {
		t.Errorf("status = %q, want active", w.Status)
	}
	if w.ArchivedAt != nil {
		t.Error("a new workspace must have no archived_at — the DB constraint would reject it")
	}
	if !w.CreatedAt.Equal(testNow) || !w.UpdatedAt.Equal(testNow) {
		t.Errorf("timestamps = %v/%v, want both %v", w.CreatedAt, w.UpdatedAt, testNow)
	}
}

// TestCreate_GeneratesIDBeforeInsert pins that the id exists on the returned
// value and is a real UUID — the whole reason ids are generated by the
// application rather than by the database.
func TestCreate_GeneratesIDBeforeInsert(t *testing.T) {
	svc, _ := newTestService()

	first, err := svc.Create(ctx(), CreateInput{Name: "One", Slug: "one"}, testEvent(audit.ActionWorkspaceCreated))
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	second, err := svc.Create(ctx(), CreateInput{Name: "Two", Slug: "two"}, testEvent(audit.ActionWorkspaceCreated))
	if err != nil {
		t.Fatalf("Create: %v", err)
	}

	if first.ID == second.ID {
		t.Error("two workspaces got the same id")
	}
	for _, w := range []*Workspace{first, second} {
		if _, err := publicid.Parse(publicid.WorkspacePrefix, w.ID); err != nil {
			t.Errorf("id %q is not a valid UUID: %v", w.ID, err)
		}
		if !strings.HasPrefix(w.PublicID(), "ws_") {
			t.Errorf("PublicID() = %q, want a ws_ prefix", w.PublicID())
		}
	}
}

func TestCreate_UsesExplicitSlugNormalizedOnly(t *testing.T) {
	svc, _ := newTestService()

	w, err := svc.Create(ctx(), CreateInput{Name: "Production", Slug: "  PROD-EU  "}, testEvent(audit.ActionWorkspaceCreated))
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if w.Slug != "prod-eu" {
		t.Errorf("slug = %q, want %q", w.Slug, "prod-eu")
	}
}

func TestCreate_RejectsBlankName(t *testing.T) {
	svc, repo := newTestService()

	for _, name := range []string{"", "   ", "\t\n"} {
		_, err := svc.Create(ctx(), CreateInput{Name: name, Slug: "valid-slug"}, testEvent(audit.ActionWorkspaceCreated))
		if !errors.Is(err, ErrNameRequired) {
			t.Errorf("Create(name=%q) = %v, want ErrNameRequired", name, err)
		}
	}
	if repo.createCalls != 0 {
		t.Errorf("repository was called %d times for invalid input; validation must short-circuit", repo.createCalls)
	}
}

func TestCreate_RejectsOverlongName(t *testing.T) {
	svc, _ := newTestService()

	_, err := svc.Create(ctx(), CreateInput{Name: strings.Repeat("a", maxNameLength+1), Slug: "ok"}, testEvent(audit.ActionWorkspaceCreated))
	if !errors.Is(err, ErrInvalidRequest) {
		t.Errorf("Create with an overlong name = %v, want ErrInvalidRequest", err)
	}
}

func TestCreate_RejectsInvalidSlug(t *testing.T) {
	svc, repo := newTestService()

	for _, slug := range []string{"My Workspace", "-lead", "trail-", "under_score", "double--hyphen", "a/b"} {
		_, err := svc.Create(ctx(), CreateInput{Name: "Valid Name", Slug: slug}, testEvent(audit.ActionWorkspaceCreated))
		if !errors.Is(err, ErrSlugInvalid) {
			t.Errorf("Create(slug=%q) = %v, want ErrSlugInvalid", slug, err)
		}
	}
	if repo.createCalls != 0 {
		t.Error("invalid slugs must be rejected before the repository is touched")
	}
}

// TestCreate_NormalizationFixesCaseAndPadding is the flip side of the test
// above: the two things NormalizeSlug does are the two things a caller does
// NOT get an error for. Anything normalization cannot fix is reported rather
// than rewritten.
func TestCreate_NormalizationFixesCaseAndPadding(t *testing.T) {
	svc, _ := newTestService()

	w, err := svc.Create(ctx(), CreateInput{Name: "Upper", Slug: "  UPPER-Case  "}, testEvent(audit.ActionWorkspaceCreated))
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if w.Slug != "upper-case" {
		t.Errorf("slug = %q, want %q", w.Slug, "upper-case")
	}
}

func TestCreate_RejectsReservedSlug(t *testing.T) {
	svc, repo := newTestService()

	for _, slug := range []string{"admin", "api", "v1", "swagger"} {
		_, err := svc.Create(ctx(), CreateInput{Name: "Some Name", Slug: slug}, testEvent(audit.ActionWorkspaceCreated))
		if !errors.Is(err, ErrSlugReserved) {
			t.Errorf("Create(slug=%q) = %v, want ErrSlugReserved", slug, err)
		}
	}
	if repo.createCalls != 0 {
		t.Error("reserved slugs must be rejected before the repository is touched")
	}
}

// TestCreate_RejectsReservedSlugDerivedFromName closes the bypass: a caller
// who cannot send `slug: "admin"` must not be able to get there by sending
// `name: "Admin"` instead.
func TestCreate_RejectsReservedSlugDerivedFromName(t *testing.T) {
	svc, _ := newTestService()

	_, err := svc.Create(ctx(), CreateInput{Name: "Admin"}, testEvent(audit.ActionWorkspaceCreated))
	if !errors.Is(err, ErrSlugReserved) {
		t.Errorf("Create(name=\"Admin\") = %v, want ErrSlugReserved", err)
	}
}

// TestCreate_RejectsUnslugifiableName covers the honest failure path: a name
// with no ASCII alphanumerics derives to "", which is reported as an invalid
// slug so the caller knows to supply one.
func TestCreate_RejectsUnslugifiableName(t *testing.T) {
	svc, _ := newTestService()

	_, err := svc.Create(ctx(), CreateInput{Name: "生产环境"}, testEvent(audit.ActionWorkspaceCreated))
	if !errors.Is(err, ErrSlugInvalid) {
		t.Errorf("Create with an unslugifiable name = %v, want ErrSlugInvalid", err)
	}
}

func TestCreate_RejectsDuplicateSlug(t *testing.T) {
	svc, _ := newTestService(activeWorkspace(fixtureIDProd, "production", "Production"))

	_, err := svc.Create(ctx(), CreateInput{Name: "Another", Slug: "production"}, testEvent(audit.ActionWorkspaceCreated))
	if !errors.Is(err, ErrSlugTaken) {
		t.Errorf("Create with a taken slug = %v, want ErrSlugTaken", err)
	}
}

// TestCreate_ArchivedSlugStaysTaken is the permanence invariant: archiving
// does not release a slug, so a reference to `production` can never come to
// mean a different workspace.
func TestCreate_ArchivedSlugStaysTaken(t *testing.T) {
	svc, _ := newTestService(archivedWorkspace(fixtureIDOld, "production", "Production"))

	_, err := svc.Create(ctx(), CreateInput{Name: "New Production", Slug: "production"}, testEvent(audit.ActionWorkspaceCreated))
	if !errors.Is(err, ErrSlugTaken) {
		t.Errorf("Create reusing an archived slug = %v, want ErrSlugTaken", err)
	}
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

func TestGet_AcceptsBothIDForms(t *testing.T) {
	svc, _ := newTestService(activeWorkspace(fixtureIDProd, "production", "Production"))

	for _, id := range []string{"ws_" + fixtureIDProd, fixtureIDProd, strings.ToUpper(fixtureIDProd)} {
		w, err := svc.Get(ctx(), id)
		if err != nil {
			t.Fatalf("Get(%q): %v", id, err)
		}
		if w.ID != fixtureIDProd {
			t.Errorf("Get(%q) returned id %q", id, w.ID)
		}
	}
}

func TestGet_ArchivedRemainsReadable(t *testing.T) {
	svc, _ := newTestService(archivedWorkspace(fixtureIDOld, "old", "Old"))

	w, err := svc.Get(ctx(), "ws_"+fixtureIDOld)
	if err != nil {
		t.Fatalf("Get on an archived workspace: %v", err)
	}
	if !w.IsArchived() {
		t.Error("expected the workspace to report archived")
	}
}

func TestGet_MissingIsNotFound(t *testing.T) {
	svc, _ := newTestService()

	_, err := svc.Get(ctx(), "ws_"+fixtureIDProd)
	if !errors.Is(err, ErrNotFound) {
		t.Errorf("Get on an absent id = %v, want ErrNotFound", err)
	}
}

// TestGet_BadIDNeverReachesRepository is the requirement that a wrong prefix
// fails before any query. It also pins that a wrong-typed id is a 400, never a
// 404 — reporting `conn_<uuid>` as "workspace not found" would answer a
// question about whether some other object exists.
func TestGet_BadIDNeverReachesRepository(t *testing.T) {
	repo := newFakeRepository()
	repo.failWith = errors.New("repository must not be reached")
	svc := NewService(repo, &fakeRunner{}, &fakeAuditWriter{})
	svc.now = fixedClock()

	for name, id := range map[string]string{
		"wrong prefix": "conn_" + fixtureIDProd,
		"no uuid":      "ws_",
		"garbage":      "not-an-id",
		"empty":        "",
		"sql-ish":      "ws_' OR 1=1--",
	} {
		t.Run(name, func(t *testing.T) {
			_, err := svc.Get(ctx(), id)
			if !errors.Is(err, ErrInvalidID) {
				t.Errorf("Get(%q) = %v, want ErrInvalidID", id, err)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// List
// ---------------------------------------------------------------------------

func TestList_DefaultsToActiveOnly(t *testing.T) {
	svc, _ := newTestService(
		activeWorkspace(fixtureIDProd, "production", "Production"),
		archivedWorkspace(fixtureIDOld, "old", "Old"),
	)

	items, err := svc.List(ctx(), "")
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(items) != 1 || items[0].Slug != "production" {
		t.Fatalf("default listing = %+v, want only the active workspace", items)
	}
}

func TestList_Filters(t *testing.T) {
	seed := []*Workspace{
		activeWorkspace(fixtureIDProd, "production", "Production"),
		activeWorkspace(fixtureIDStaging, "staging", "Staging"),
		archivedWorkspace(fixtureIDOld, "old", "Old"),
	}

	tests := map[string]int{
		"active":   2,
		"archived": 1,
		"all":      3,
	}

	for filter, want := range tests {
		t.Run(filter, func(t *testing.T) {
			svc, _ := newTestService(seed...)
			items, err := svc.List(ctx(), filter)
			if err != nil {
				t.Fatalf("List(%q): %v", filter, err)
			}
			if len(items) != want {
				t.Errorf("List(%q) returned %d items, want %d", filter, len(items), want)
			}
		})
	}
}

// TestList_RejectsUnknownFilter pins that a typo is an error rather than a
// silent fallback. `status=achieved` quietly returning the active set would be
// actively misleading.
func TestList_RejectsUnknownFilter(t *testing.T) {
	svc, _ := newTestService()

	for _, filter := range []string{"achieved", "ACTIVE", "deleted", "true", "1"} {
		_, err := svc.List(ctx(), filter)
		if !errors.Is(err, ErrInvalidStatusFilter) {
			t.Errorf("List(%q) = %v, want ErrInvalidStatusFilter", filter, err)
		}
	}
}

func TestList_OrdersByNameThenID(t *testing.T) {
	// Two workspaces share a name, so the id tiebreaker is what makes the
	// order deterministic.
	svc, _ := newTestService(
		activeWorkspace(fixtureIDStaging, "staging", "Shared"),
		activeWorkspace(fixtureIDProd, "production", "Shared"),
		activeWorkspace(fixtureIDOld, "alpha", "Alpha"),
	)

	items, err := svc.List(ctx(), "active")
	if err != nil {
		t.Fatalf("List: %v", err)
	}

	want := []string{"Alpha", "Shared", "Shared"}
	for i, w := range want {
		if items[i].Name != w {
			t.Fatalf("position %d = %q, want %q (order: %+v)", i, items[i].Name, w, items)
		}
	}
	if items[1].ID > items[2].ID {
		t.Errorf("equal names not tie-broken by id: %q then %q", items[1].ID, items[2].ID)
	}
}

// ---------------------------------------------------------------------------
// UpdateName
// ---------------------------------------------------------------------------

func TestUpdateName_RenamesAndStampsUpdatedAt(t *testing.T) {
	svc, _ := newTestService(activeWorkspace(fixtureIDProd, "production", "Production"))

	w, err := svc.UpdateName(ctx(), "ws_"+fixtureIDProd, "  Production EU  ", testEvent(audit.ActionWorkspaceRenamed))
	if err != nil {
		t.Fatalf("UpdateName: %v", err)
	}
	if w.Name != "Production EU" {
		t.Errorf("name = %q, want it trimmed", w.Name)
	}
	if !w.UpdatedAt.Equal(testNow) {
		t.Errorf("updated_at = %v, want %v", w.UpdatedAt, testNow)
	}
}

// TestUpdateName_LeavesSlugUntouched is the immutability invariant at the
// service level. The handler rejects a slug in the payload outright; this pins
// that even the permitted operation cannot move it.
func TestUpdateName_LeavesSlugUntouched(t *testing.T) {
	svc, _ := newTestService(activeWorkspace(fixtureIDProd, "production", "Production"))

	w, err := svc.UpdateName(ctx(), "ws_"+fixtureIDProd, "Completely Different Name", testEvent(audit.ActionWorkspaceRenamed))
	if err != nil {
		t.Fatalf("UpdateName: %v", err)
	}
	if w.Slug != "production" {
		t.Errorf("slug changed to %q — slug is immutable", w.Slug)
	}
	if w.Status != StatusActive || w.ArchivedAt != nil {
		t.Errorf("status/archived_at moved: %q / %v", w.Status, w.ArchivedAt)
	}
}

func TestUpdateName_RejectsBlankName(t *testing.T) {
	svc, _ := newTestService(activeWorkspace(fixtureIDProd, "production", "Production"))

	for _, name := range []string{"", "   "} {
		_, err := svc.UpdateName(ctx(), "ws_"+fixtureIDProd, name, testEvent(audit.ActionWorkspaceRenamed))
		if !errors.Is(err, ErrNameRequired) {
			t.Errorf("UpdateName(%q) = %v, want ErrNameRequired", name, err)
		}
	}
}

func TestUpdateName_RejectsArchived(t *testing.T) {
	svc, _ := newTestService(archivedWorkspace(fixtureIDOld, "old", "Old"))

	_, err := svc.UpdateName(ctx(), "ws_"+fixtureIDOld, "New Name", testEvent(audit.ActionWorkspaceRenamed))
	if !errors.Is(err, ErrArchived) {
		t.Errorf("UpdateName on an archived workspace = %v, want ErrArchived", err)
	}
}

func TestUpdateName_MissingIsNotFound(t *testing.T) {
	svc, _ := newTestService()

	_, err := svc.UpdateName(ctx(), "ws_"+fixtureIDProd, "Name", testEvent(audit.ActionWorkspaceRenamed))
	if !errors.Is(err, ErrNotFound) {
		t.Errorf("UpdateName on an absent id = %v, want ErrNotFound", err)
	}
}

// ---------------------------------------------------------------------------
// Archive
// ---------------------------------------------------------------------------

func TestArchive_TransitionsActiveToArchived(t *testing.T) {
	svc, _ := newTestService(activeWorkspace(fixtureIDProd, "production", "Production"))

	w, err := svc.Archive(ctx(), "ws_"+fixtureIDProd, testEvent(audit.ActionWorkspaceArchived))
	if err != nil {
		t.Fatalf("Archive: %v", err)
	}

	if w.Status != StatusArchived {
		t.Errorf("status = %q, want archived", w.Status)
	}
	if w.ArchivedAt == nil {
		t.Fatal("archived_at must be set — the DB constraint requires it for archived rows")
	}
	if !w.ArchivedAt.Equal(testNow) {
		t.Errorf("archived_at = %v, want %v", w.ArchivedAt, testNow)
	}
	if w.Slug != "production" {
		t.Errorf("slug changed to %q — archiving must not release the slug", w.Slug)
	}
}

// TestArchive_IsIdempotent is the retry-safety requirement: a client that
// times out and retries must get the same answer, not a spurious conflict.
func TestArchive_IsIdempotent(t *testing.T) {
	svc, _ := newTestService(activeWorkspace(fixtureIDProd, "production", "Production"))

	first, err := svc.Archive(ctx(), "ws_"+fixtureIDProd, testEvent(audit.ActionWorkspaceArchived))
	if err != nil {
		t.Fatalf("first Archive: %v", err)
	}

	for i := 0; i < 3; i++ {
		again, err := svc.Archive(ctx(), "ws_"+fixtureIDProd, testEvent(audit.ActionWorkspaceArchived))
		if err != nil {
			t.Fatalf("repeat Archive %d: %v", i, err)
		}
		if again.Status != StatusArchived {
			t.Errorf("repeat %d: status = %q, want archived", i, again.Status)
		}
		if !again.ArchivedAt.Equal(*first.ArchivedAt) {
			t.Errorf("repeat %d moved archived_at from %v to %v — the original timestamp must stand",
				i, first.ArchivedAt, again.ArchivedAt)
		}
	}
}

func TestArchive_MissingIsNotFound(t *testing.T) {
	svc, _ := newTestService()

	_, err := svc.Archive(ctx(), "ws_"+fixtureIDProd, testEvent(audit.ActionWorkspaceArchived))
	if !errors.Is(err, ErrNotFound) {
		t.Errorf("Archive on an absent id = %v, want ErrNotFound", err)
	}
}

func TestArchive_RejectsBadID(t *testing.T) {
	svc, _ := newTestService()

	_, err := svc.Archive(ctx(), "conn_"+fixtureIDProd, testEvent(audit.ActionWorkspaceArchived))
	if !errors.Is(err, ErrInvalidID) {
		t.Errorf("Archive with a wrong prefix = %v, want ErrInvalidID", err)
	}
}

// ---------------------------------------------------------------------------
// Repository failure propagation
// ---------------------------------------------------------------------------

// TestService_PropagatesRepositoryFailures pins that an unexpected storage
// error is passed up unchanged rather than being flattened into a domain
// error. The handler is what turns it into internal_error, so flattening here
// would lose the cause before it could be logged.
func TestService_PropagatesRepositoryFailures(t *testing.T) {
	boom := errors.New("connection reset")
	repo := newFakeRepository(activeWorkspace(fixtureIDProd, "production", "Production"))
	repo.failWith = boom
	svc := NewService(repo, &fakeRunner{}, &fakeAuditWriter{})
	svc.now = fixedClock()

	calls := map[string]func() error{
		"Create": func() error {
			_, err := svc.Create(ctx(), CreateInput{Name: "X", Slug: "x"}, testEvent(audit.ActionWorkspaceCreated))
			return err
		},
		"Get":  func() error { _, err := svc.Get(ctx(), "ws_"+fixtureIDProd); return err },
		"List": func() error { _, err := svc.List(ctx(), "active"); return err },
		"UpdateName": func() error {
			_, err := svc.UpdateName(ctx(), "ws_"+fixtureIDProd, "Y", testEvent(audit.ActionWorkspaceRenamed))
			return err
		},
		"Archive": func() error {
			_, err := svc.Archive(ctx(), "ws_"+fixtureIDProd, testEvent(audit.ActionWorkspaceArchived))
			return err
		},
	}

	for name, call := range calls {
		t.Run(name, func(t *testing.T) {
			if err := call(); !errors.Is(err, boom) {
				t.Errorf("error = %v, want the repository's error unwrapped", err)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// StatusFilter
// ---------------------------------------------------------------------------

func TestParseStatusFilter(t *testing.T) {
	tests := map[string]StatusFilter{
		"":         FilterActive,
		"active":   FilterActive,
		"archived": FilterArchived,
		"all":      FilterAll,
	}
	for in, want := range tests {
		got, err := ParseStatusFilter(in)
		if err != nil {
			t.Fatalf("ParseStatusFilter(%q): %v", in, err)
		}
		if got != want {
			t.Errorf("ParseStatusFilter(%q) = %q, want %q", in, got, want)
		}
	}

	if _, err := ParseStatusFilter("nope"); !errors.Is(err, ErrInvalidStatusFilter) {
		t.Errorf("ParseStatusFilter(\"nope\") = %v, want ErrInvalidStatusFilter", err)
	}
}
