// Package publicid renders and parses the prefixed identifiers the public API
// exposes: a UUID stored in the database becomes `ws_<uuid>` on the wire.
//
// Why prefix at all. An opaque UUID in a log line, a bug report or a support
// ticket says nothing about what it identifies, and an id pasted into the wrong
// endpoint fails as "not found" — indistinguishable from a genuine 404. A
// prefix makes the type visible to humans and lets the API reject a
// wrong-typed id before it ever reaches the database.
//
// Scope. This is a formatting helper, not an identifier framework: no
// registry, no interfaces, no type parameters. The prefix is a plain argument,
// so `conn_` and `prj_` need no change here — just a different constant at the
// call site.
package publicid

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"strings"
)

// Prefixes in use. New domains add a constant here so the set is greppable in
// one place rather than scattered as string literals.
const (
	// WorkspacePrefix renders workspace ids as ws_<uuid>.
	WorkspacePrefix = "ws"

	// ConnectionPrefix renders connection ids as conn_<uuid>.
	ConnectionPrefix = "conn"

	// ProjectPrefix renders project ids as prj_<uuid>. A Project is a backend
	// that consumes this API on behalf of exactly one workspace.
	ProjectPrefix = "prj"

	// CredentialPrefix renders project-credential ids as key_<uuid>.
	//
	// This is the id of the credential ROW — what appears in audit events and
	// in the console. It is deliberately NOT the lookup segment inside the
	// credential's token: keeping the two distinct means the identifier an
	// operator quotes in a ticket is never a substring of a secret.
	CredentialPrefix = "key"
)

// separator between the prefix and the UUID. Underscore rather than a hyphen
// or colon: a UUID already contains hyphens, and `ws_...` survives being
// double-clicked, put in a URL path, or used as a shell word without quoting.
const separator = "_"

var (
	// ErrWrongPrefix means the id is well-formed but names a different kind of
	// object — `conn_<uuid>` passed where a workspace was expected. Callers
	// should treat it as a client error, never as "not found".
	ErrWrongPrefix = errors.New("publicid: wrong prefix")

	// ErrMalformed means the value is not a public id at all: empty, missing
	// the UUID, or carrying something that is not a canonical UUID.
	ErrMalformed = errors.New("publicid: malformed identifier")
)

// Format renders a canonical UUID as a prefixed public id.
//
// It does not validate uuid — callers pass values that came out of the
// database or out of New, both of which are already canonical. Formatting is
// on the response path of every request, and a validation pass there would buy
// nothing that the CHECK constraint and New do not already guarantee.
func Format(prefix, uuid string) string {
	return prefix + separator + uuid
}

// Parse accepts either the prefixed form (`ws_<uuid>`) or a bare UUID, and
// returns the canonical lowercase UUID for use in a query.
//
// The bare form is accepted deliberately: it makes `curl` against a value
// copied straight out of psql work during development, and it means an
// operator debugging an incident does not have to re-prefix ids by hand. It
// costs nothing in safety, because a bare UUID cannot be a *wrong-typed* id —
// only a prefixed one carries a type to get wrong.
//
// Returns ErrWrongPrefix when a different prefix is present, and ErrMalformed
// for anything that is not a UUID. Both are client errors; neither should ever
// be reported as a missing object.
func Parse(prefix, s string) (string, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", ErrMalformed
	}

	if before, after, found := strings.Cut(s, separator); found {
		if before != prefix {
			return "", ErrWrongPrefix
		}
		s = after
	}

	uuid, ok := normalizeUUID(s)
	if !ok {
		return "", ErrMalformed
	}
	return uuid, nil
}

// New generates a random (version 4) UUID in canonical form.
//
// Ids are generated by the application rather than the database so the value
// is known before the INSERT — it can be logged, returned, and referenced
// inside the same transaction. crypto/rand is the only source; a failure to
// read it is returned rather than silently degraded, because a predictable
// identifier is a security property, not a cosmetic one.
func New() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	// RFC 4122 §4.4: set the version to 4 and the variant to 10xx.
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80

	buf := make([]byte, 36)
	hex.Encode(buf[0:8], b[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], b[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], b[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], b[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:36], b[10:16])
	return string(buf), nil
}

// normalizeUUID validates the canonical 8-4-4-4-12 hyphenated form and returns
// it lowercased. Uppercase input is accepted because PostgreSQL accepts it and
// normalizes the same way; rejecting it would make the API stricter than the
// storage it fronts for no gain.
//
// Only the canonical form is accepted — not the braced or URN variants, and
// not the unhyphenated 32-character form. Accepting several spellings of the
// same id means the same object has several public names, which defeats the
// point of having a public id at all.
func normalizeUUID(s string) (string, bool) {
	if len(s) != 36 {
		return "", false
	}
	for i := 0; i < 36; i++ {
		c := s[i]
		if i == 8 || i == 13 || i == 18 || i == 23 {
			if c != '-' {
				return "", false
			}
			continue
		}
		switch {
		case c >= '0' && c <= '9',
			c >= 'a' && c <= 'f',
			c >= 'A' && c <= 'F':
		default:
			return "", false
		}
	}
	return strings.ToLower(s), true
}
