package bootstrap

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DevPlaygroundClientID is the public OIDC client id used by the browser-
// based dev auth playground (PKCE flow). Hardcoded because the playground
// HTML/JS shipped in web/dev/ is also DEV-ONLY and doesn't need this
// configurable — flipping features.dev_playground in project.json controls
// whether it's registered at all.
const DevPlaygroundClientID = "saas-dev-playground"

// Secrets are the credentials that never enter project.json. They are read
// from .env on regen and prompted for on `make init`.
type Secrets struct {
	AdminPassword    string
	ClientSecret     string
	SeedUserPassword string
}

// defaultSecrets returns dev-friendly placeholders used when no .env exists.
func defaultSecrets() Secrets {
	return Secrets{
		AdminPassword:    "admin",
		ClientSecret:     "saas-backend-secret",
		SeedUserPassword: "password",
	}
}

// LoadSecrets reads credentials from <repoRoot>/.env. Missing or unset values
// fall back to defaultSecrets so a fresh clone produces a working stack.
func LoadSecrets(repoRoot string) Secrets {
	s := defaultSecrets()
	data, err := os.ReadFile(filepath.Join(repoRoot, ".env"))
	if err != nil {
		return s
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		v = strings.TrimSpace(v)
		switch k {
		case "KEYCLOAK_ADMIN_PASSWORD":
			if v != "" {
				s.AdminPassword = v
			}
		case "KEYCLOAK_CLIENT_SECRET":
			if v != "" {
				s.ClientSecret = v
			}
		case "SEED_USER_PASSWORD":
			if v != "" {
				s.SeedUserPassword = v
			}
		}
	}
	return s
}

// GenerateAll regenerates every file owned by the bootstrap layer from the
// given ProjectConfig + Secrets. Paths are resolved relative to repoRoot.
//
// Owned files (rewritten in place):
//   - .env
//   - .env.example
//   - config/project.schema.json   (mirror of the embedded canonical copy)
//   - deploy/keycloak/realm-export.json
//
// TODO (future): docker-compose override, README snippet, frontend env file.
func GenerateAll(repoRoot string, cfg *ProjectConfig, secrets Secrets) error {
	if err := writeEnv(filepath.Join(repoRoot, ".env"), cfg, secrets, false); err != nil {
		return err
	}
	if err := writeEnv(filepath.Join(repoRoot, ".env.example"), cfg, defaultSecrets(), true); err != nil {
		return err
	}
	if err := writeSchemaFile(filepath.Join(repoRoot, "config/project.schema.json")); err != nil {
		return err
	}
	if err := writeRealmExport(filepath.Join(repoRoot, "deploy/keycloak/realm-export.json"), cfg, secrets); err != nil {
		return err
	}
	return nil
}

// writeSchemaFile materializes the embedded canonical schema to disk.
// IDEs reference it via the $schema key in project.json — the file must
// exist at that path. The embedded copy stays the source of truth.
func writeSchemaFile(path string) error {
	return os.WriteFile(path, schemaJSON, 0o644)
}

// writeEnv emits a deterministic .env file. annotate=true adds the inline
// guidance suitable for .env.example; false omits it for the working .env.
// All secret values come from the Secrets parameter — they are never sourced
// from cfg, which is committed to git.
func writeEnv(path string, cfg *ProjectConfig, secrets Secrets, annotate bool) error {
	var b strings.Builder
	hdr := func(s string) {
		b.WriteString("# =====================================================\n")
		b.WriteString("# " + s + "\n")
		b.WriteString("# =====================================================\n")
	}

	if annotate {
		b.WriteString("# Auto-generated by `make init` / cmd/bootstrap. Edit config/project.json\n")
		b.WriteString("# (and re-run `make regen`) rather than editing this file by hand.\n")
		b.WriteString("# Secrets are sourced from this .env at regeneration time and preserved.\n\n")
	}

	hdr("APPLICATION DATABASE")
	b.WriteString("POSTGRES_USER=postgres\n")
	b.WriteString("POSTGRES_PASSWORD=postgres\n")
	b.WriteString(fmt.Sprintf("POSTGRES_DB=%s_db\n", sanitize(cfg.Project.Name)))
	b.WriteString(fmt.Sprintf("DB_URL=postgres://postgres:postgres@localhost:%d/%s_db?sslmode=disable\n\n",
		cfg.Ports.Postgres, sanitize(cfg.Project.Name)))

	hdr("KEYCLOAK DATABASE")
	b.WriteString("KC_DB_USER=keycloak\n")
	b.WriteString("KC_DB_PASSWORD=keycloak\n")
	b.WriteString("KC_DB_NAME=keycloak\n\n")

	hdr("KEYCLOAK ADMIN BOOTSTRAP\n# !!! DEV-ONLY DEFAULTS — rotate before any non-local deployment.")
	b.WriteString(fmt.Sprintf("KEYCLOAK_ADMIN=%s\n", cfg.Auth.Admin.Username))
	b.WriteString(fmt.Sprintf("KEYCLOAK_ADMIN_PASSWORD=%s\n\n", secrets.AdminPassword))

	hdr("KEYCLOAK CLIENT CONFIGURATION")
	b.WriteString(fmt.Sprintf("KEYCLOAK_URL=http://localhost:%d\n", cfg.Ports.Keycloak))
	b.WriteString(fmt.Sprintf("KEYCLOAK_REALM=%s\n", cfg.Auth.Realm))
	b.WriteString(fmt.Sprintf("KEYCLOAK_CLIENT_ID=%s\n", cfg.Auth.Client.ID))
	b.WriteString(fmt.Sprintf("KEYCLOAK_CLIENT_SECRET=%s\n", secrets.ClientSecret))
	b.WriteString("KEYCLOAK_JWKS_URL=\n")
	b.WriteString(fmt.Sprintf("# Whitelist of token-issuing client ids (azp claim). Override in\n# project.json via auth.allowed_client_ids; otherwise derived from\n# auth.client.id + dev_playground client when the feature is on.\nKEYCLOAK_ALLOWED_CLIENT_IDS=%s\n\n", strings.Join(allowedClientIDs(cfg), ",")))

	hdr("SEED USER PASSWORD (shared across all seed users defined in project.json)")
	b.WriteString(fmt.Sprintf("SEED_USER_PASSWORD=%s\n\n", secrets.SeedUserPassword))

	hdr("APP")
	b.WriteString(fmt.Sprintf("PORT=%d\n", cfg.Ports.API))
	b.WriteString("GIN_LOG_ENABLED=true\n")
	b.WriteString("GIN_ACCESS_LOG_ENABLED=true\n\n")

	hdr("DEV AUTH PLAYGROUND\n# Driven by features.dev_playground in config/project.json.\n# !!! DEV-ONLY — exposes a login playground at /dev/auth.")
	if cfg.Features["dev_playground"] {
		b.WriteString("DEV_PLAYGROUND_ENABLED=true\n")
	} else {
		b.WriteString("DEV_PLAYGROUND_ENABLED=false\n")
	}
	b.WriteString(fmt.Sprintf("DEV_PLAYGROUND_CLIENT_ID=%s\n", DevPlaygroundClientID))

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// writeRealmExport regenerates the Keycloak realm import file by composing a
// minimal JSON shape from the project config and serializing deterministically.
// Secret values (client secret, seed user passwords) come exclusively from
// the Secrets parameter — never from cfg.
func writeRealmExport(path string, cfg *ProjectConfig, secrets Secrets) error {
	realmRoles := make([]map[string]any, 0, len(cfg.Auth.Roles))
	for _, r := range cfg.Auth.Roles {
		realmRoles = append(realmRoles, map[string]any{
			"name":        r,
			"description": fmt.Sprintf("realm role: %s", r),
		})
	}

	// NOTE: defaultClientScopes is intentionally omitted so Keycloak applies
	// its realm-level default scope set (basic + email + profile + roles +
	// web-origins + acr). The "basic" scope is what attaches the sub mapper
	// — overriding the list here would drop sub from issued tokens, which
	// breaks the provider's identityFromClaims invariant.
	client := map[string]any{
		"clientId":                  cfg.Auth.Client.ID,
		"name":                      cfg.Project.Name + " API",
		"enabled":                   true,
		"protocol":                  "openid-connect",
		"publicClient":              false,
		"secret":                    secrets.ClientSecret,
		"standardFlowEnabled":       true,
		"directAccessGrantsEnabled": true,
		"serviceAccountsEnabled":    false,
		"redirectUris":              []string{fmt.Sprintf("http://localhost:%d/*", cfg.Ports.API)},
		"webOrigins":                []string{fmt.Sprintf("http://localhost:%d", cfg.Ports.API)},
	}

	clients := []map[string]any{client}

	// When features.dev_playground is on, register a SECOND public client
	// for the in-browser auth playground at /dev/auth. Public-PKCE-only:
	// no client secret, S256 challenge enforced. Mirrors how a real
	// frontend (keycloak-js) would integrate.
	if cfg.Features["dev_playground"] {
		clients = append(clients, map[string]any{
			"clientId":                  DevPlaygroundClientID,
			"name":                      cfg.Project.Name + " — Dev Auth Playground",
			"description":               "DEV-ONLY public PKCE client for the in-browser auth playground at /dev/auth. Disable in non-local environments.",
			"enabled":                   true,
			"protocol":                  "openid-connect",
			"publicClient":              true,
			"standardFlowEnabled":       true,
			"directAccessGrantsEnabled": false,
			"serviceAccountsEnabled":    false,
			"redirectUris": []string{
				fmt.Sprintf("http://localhost:%d/dev/auth", cfg.Ports.API),
			},
			"webOrigins": []string{fmt.Sprintf("http://localhost:%d", cfg.Ports.API)},
			"attributes": map[string]any{
				"pkce.code.challenge.method": "S256",
				"post.logout.redirect.uris":  fmt.Sprintf("http://localhost:%d/dev/auth", cfg.Ports.API),
			},
		})
	}

	var users []map[string]any
	if cfg.Features["seed_users"] {
		for _, u := range cfg.SeedUsers {
			// firstName/lastName are required by the default user-profile
			// schema for any user with the "user" role. Derive from the
			// username when the SeedUser doesn't supply them explicitly,
			// so seeded accounts can complete password-grant logins.
			first, last := splitDisplayName(u.Username)
			users = append(users, map[string]any{
				"username":      u.Username,
				"enabled":       true,
				"emailVerified": true,
				"email":         u.Email,
				"firstName":     first,
				"lastName":      last,
				"credentials": []map[string]any{
					{"type": "password", "value": secrets.SeedUserPassword, "temporary": false},
				},
				"realmRoles": u.Roles,
			})
		}
	}

	// NOTE: Keycloak's realm parser rejects unknown top-level fields, so the
	// DEV-ONLY warning lives in docs/bootstrap.md and config/project.json
	// (in _meta), not in this generated artifact.
	realm := map[string]any{
		"realm":                  cfg.Auth.Realm,
		"enabled":                true,
		"displayName":            cfg.Project.Name,
		"sslRequired":            "none",
		"registrationAllowed":    false,
		"loginWithEmailAllowed":  true,
		"duplicateEmailsAllowed": false,
		"resetPasswordAllowed":   true,
		"editUsernameAllowed":    false,
		"bruteForceProtected":    true,
		"accessTokenLifespan":    3600,
		"ssoSessionIdleTimeout":  1800,
		"ssoSessionMaxLifespan":  36000,
		"roles":                  map[string]any{"realm": realmRoles},
		"clients":                clients,
		"users":                  users,
	}

	b, err := json.MarshalIndent(realm, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal realm: %w", err)
	}
	b = append(b, '\n')
	return os.WriteFile(path, b, 0o644)
}

// allowedClientIDs computes the deduplicated list of token-issuing client
// ids that the API should accept (used to populate KEYCLOAK_ALLOWED_CLIENT_IDS
// in .env).
//
// Precedence:
//  1. cfg.Auth.AllowedClientIDs — explicit override from project.json.
//  2. Auto-derive from registered clients:
//     - auth.client.id (always)
//     - DevPlaygroundClientID (when features.dev_playground=true)
//
// Order is preserved with the primary client first so logs/configs are
// stable across regens.
func allowedClientIDs(cfg *ProjectConfig) []string {
	if len(cfg.Auth.AllowedClientIDs) > 0 {
		seen := map[string]struct{}{}
		out := make([]string, 0, len(cfg.Auth.AllowedClientIDs))
		for _, id := range cfg.Auth.AllowedClientIDs {
			if id == "" {
				continue
			}
			if _, dup := seen[id]; dup {
				continue
			}
			seen[id] = struct{}{}
			out = append(out, id)
		}
		return out
	}
	list := []string{cfg.Auth.Client.ID}
	if cfg.Features["dev_playground"] {
		list = append(list, DevPlaygroundClientID)
	}
	return list
}

// splitDisplayName produces (firstName, lastName) pairs from a username
// when the SeedUser doesn't supply them. Used to satisfy Keycloak's
// default user-profile schema, which requires firstName/lastName for any
// user holding the "user" role.
//
// Rules:
//   - Splits on common separators (".", "-", "_", " ")
//   - Returns (Capitalize(part0), Capitalize(part1...)) when separable
//   - Otherwise returns (Capitalize(username), "User")
func splitDisplayName(username string) (string, string) {
	for _, sep := range []string{".", "-", "_", " "} {
		if i := strings.Index(username, sep); i > 0 && i < len(username)-1 {
			return capFirst(username[:i]), capFirst(username[i+len(sep):])
		}
	}
	return capFirst(username), "User"
}

func capFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] = r[0] - 32
	}
	return string(r)
}

// sanitize collapses a project name into a database-friendly identifier:
// lowercase, dashes/spaces -> underscores, strip non-[a-z0-9_].
func sanitize(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		case r == '-' || r == ' ' || r == '.':
			b.WriteRune('_')
		}
	}
	out := b.String()
	if out == "" {
		out = "app"
	}
	return out
}
