-- 000002_workspaces — the first table of the Identity Control Plane domain.
--
-- A Workspace is an isolated administrative context. It will later own a
-- Connection to an identity provider; today it owns nothing and performs no
-- Keycloak operation. Nothing in this migration touches `users` (000001).
--
-- No workspace row is seeded. The first workspace is created through the API,
-- and migrating the current single-Keycloak configuration into one belongs
-- with Connection, when there is a real configuration to migrate.
--
-- IDENTIFIERS. `id` is a native `uuid` generated by the application before the
-- INSERT, not by the database. That keeps the value knowable before the write
-- (so it can be logged, returned, or referenced inside the same transaction)
-- and avoids depending on pgcrypto / gen_random_uuid() availability. The API
-- never exposes the bare UUID — it renders `ws_<uuid>` (internal/publicid).
--
-- THE CHECK CONSTRAINTS ARE THE POINT. Application validation is the first
-- line, but it is the line that a future bug, a manual `psql` session, or a
-- second writer can walk around. These three constraints make the invariants
-- true of the data rather than true of one code path:
--
--   status         — only 'active' or 'archived' can exist at all
--   archived_at    — set if and only if archived; the two can never disagree
--   slug format    — the normalized form the API promises is enforced at rest
--
-- Idempotent (IF NOT EXISTS on the table and both indexes) to match 000001's
-- convention, so a retried deploy re-runs cleanly. Table constraints ride
-- along with CREATE TABLE, so they need no separate guard.

CREATE TABLE IF NOT EXISTS workspaces (
    id          uuid        PRIMARY KEY,
    slug        text        NOT NULL,
    name        text        NOT NULL,
    status      text        NOT NULL DEFAULT 'active',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    archived_at timestamptz NULL,

    CONSTRAINT workspaces_status_check
        CHECK (status IN ('active', 'archived')),

    -- Biconditional, not a one-way implication: an active row with an
    -- archived_at timestamp is just as corrupt as an archived row without one.
    CONSTRAINT workspaces_archived_at_check
        CHECK (
            (status = 'archived' AND archived_at IS NOT NULL)
            OR
            (status = 'active' AND archived_at IS NULL)
        ),

    -- Lowercase alphanumeric groups joined by single hyphens: no leading,
    -- trailing or doubled hyphen, no uppercase, no whitespace. 63 characters
    -- matches the DNS label limit, which is the shape a slug will eventually
    -- have to fit if workspaces ever become subdomains.
    CONSTRAINT workspaces_slug_format_check
        CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND length(slug) <= 63),

    CONSTRAINT workspaces_name_not_blank_check
        CHECK (length(btrim(name)) > 0)
);

-- Slug uniqueness is global and permanent: archiving does not release a slug,
-- so a reference to `production` can never silently come to mean a different
-- workspace. A partial index over active rows would have released it.
CREATE UNIQUE INDEX IF NOT EXISTS idx_workspaces_slug ON workspaces (slug);

-- Serves the default listing, which filters on status and orders by
-- (name, id) — the whole query is covered by this one index.
CREATE INDEX IF NOT EXISTS idx_workspaces_status_name_id ON workspaces (status, name, id);
