-- 000005_projects — Projects and their machine credentials.
--
-- A Project is a backend that consumes this API on behalf of ONE workspace. A
-- Project Credential is how that backend authenticates: an opaque API key, not
-- an operator token.
--
-- THE CREDENTIAL SECRET IS NEVER STORED. What is stored is `key_prefix` (the
-- public lookup segment, in clear, so authentication is one indexed SELECT) and
-- `key_hash` (SHA-256 of the secret segment). The plaintext exists only in the
-- response body of the create call and nowhere else in this system. Unlike
-- connections.secret_ciphertext, this is a DIGEST and not a sealed value: there
-- is no operation that needs the secret back, so nothing reversible is kept.
--
-- SHA-256 rather than bcrypt/Argon2 is deliberate and is not a password
-- shortcut. The secret is 256 bits of CSPRNG output generated by this service;
-- password hashes exist to slow down guessing of low-entropy human input, and
-- there is no such search space here. A memory-hard hash on the authentication
-- path of a machine-to-machine API would be a self-inflicted DoS and would buy
-- nothing. `key_hash_alg` is stored so changing that judgement later is a
-- migration rather than a redesign.
--
-- ONE WORKSPACE PER PROJECT, permanently. The workspace_id column is the whole
-- authorization boundary: it is compared against the workspace in the request
-- path before any workspace, connection or provider is touched. A project that
-- could span workspaces would turn that string comparison into a lookup, and
-- the guarantee "one leaked credential reaches one realm" into a query result.
--
-- Idempotent (IF NOT EXISTS throughout), matching 000001-000004, so a retried
-- deploy re-runs cleanly.

CREATE TABLE IF NOT EXISTS projects (
    id uuid PRIMARY KEY,

    -- ON DELETE RESTRICT, as connections.workspace_id. Workspaces are archived
    -- and never deleted, so a cascade could only ever fire from a manual psql
    -- session — exactly when silently destroying a tenant's API access is
    -- least wanted.
    workspace_id uuid NOT NULL REFERENCES workspaces (id) ON DELETE RESTRICT,

    name   text NOT NULL,
    status text NOT NULL DEFAULT 'active',

    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    archived_at timestamptz NULL,

    CONSTRAINT projects_status_check
        CHECK (status IN ('active', 'archived')),

    -- status and archived_at can never disagree, in either direction. Same
    -- shape as workspaces_archived_at_check: the pair is written in one
    -- statement so the constraint is never even transiently violated.
    CONSTRAINT projects_archived_at_check
        CHECK ((status = 'archived') = (archived_at IS NOT NULL)),

    CONSTRAINT projects_name_not_blank
        CHECK (length(btrim(name)) > 0)
);

-- Names are unique per workspace, case-insensitively.
--
-- There is no slug here, unlike workspaces. A slug exists to be a stable handle
-- other systems reference, and nothing references a project by name — the
-- public id does that. What the name has to solve is an operator picking the
-- wrong entry out of a list, and case-insensitive uniqueness per workspace
-- solves exactly that, without adding a second identifier to keep in sync.
CREATE UNIQUE INDEX IF NOT EXISTS projects_workspace_name_key
    ON projects (workspace_id, lower(name));

CREATE INDEX IF NOT EXISTS projects_workspace_idx
    ON projects (workspace_id);

CREATE TABLE IF NOT EXISTS project_credentials (
    id uuid PRIMARY KEY,

    project_id uuid NOT NULL REFERENCES projects (id) ON DELETE RESTRICT,

    -- Operator-supplied label, e.g. "billing worker (staging)". It is what an
    -- operator recognises the key by; the public id is what a machine does.
    label text NOT NULL,

    -- The public lookup segment of the token, stored in clear. UNIQUE because
    -- two credentials sharing one would make authentication ambiguous, and
    -- indexed because it is what turns authentication into a single row fetch
    -- instead of a scan over hashes.
    key_prefix text NOT NULL,

    -- SHA-256 of the token's secret segment. bytea, not text: this is a digest,
    -- and storing it as a string would invite something to try to read it.
    key_hash     bytea NOT NULL,
    key_hash_alg text  NOT NULL DEFAULT 'sha256',

    -- Effective scopes for THIS credential, not for the project. That is what
    -- lets one backend hold a read-only key and a read-write key at the same
    -- time, with different blast radii.
    scopes text[] NOT NULL,

    expires_at timestamptz NULL,
    revoked_at timestamptz NULL,

    -- Keycloak `sub` of the operator, not a foreign key: operators live in the
    -- identity provider, not in a table here.
    created_by text NOT NULL,
    revoked_by text NULL,

    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz NULL,

    CONSTRAINT project_credentials_label_not_blank
        CHECK (length(btrim(label)) > 0),

    CONSTRAINT project_credentials_scopes_not_empty
        CHECK (cardinality(scopes) > 0),

    -- The known-scope set lives in the database as well as in Go. A scope that
    -- reaches this table without being in the vocabulary is an application bug
    -- that would otherwise persist silently and be granted forever; here it is
    -- a failed INSERT. Adding a scope is a migration, which is correct: a new
    -- scope is a change to the authorization contract.
    CONSTRAINT project_credentials_scopes_known
        CHECK (scopes <@ ARRAY[
            'users:read', 'users:write',
            'roles:read', 'roles:write',
            'sessions:read', 'sessions:revoke',
            'invitations:read', 'invitations:write'
        ]::text[]),

    CONSTRAINT project_credentials_hash_length
        CHECK (octet_length(key_hash) = 32),

    CONSTRAINT project_credentials_revoked_by_check
        CHECK ((revoked_at IS NULL) = (revoked_by IS NULL))
);

-- The authentication lookup. UNIQUE is the correctness property, not a
-- performance one: a duplicate prefix would make "which credential is this?"
-- ambiguous at the moment it matters most.
CREATE UNIQUE INDEX IF NOT EXISTS project_credentials_key_prefix_key
    ON project_credentials (key_prefix);

CREATE INDEX IF NOT EXISTS project_credentials_project_idx
    ON project_credentials (project_id);

-- Partial index over live credentials only. Used to enforce the per-project
-- cap without paying for the revoked history, which never shrinks.
CREATE INDEX IF NOT EXISTS project_credentials_active_idx
    ON project_credentials (project_id)
    WHERE revoked_at IS NULL;
